{{- if .Values.secretProvider.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
spec:
  provider: azure
  {{- with .Values.secretOjbects }}
  secretObjects:                                      # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: {{ .key }}                                 # data field to populate
      objectName: {{ .kvObjectName }}                 # name of the mounted content to sync. this could be the object name or the object alias
    secretName: {{ .secretName }}                     # name of the Kubernetes Secret object
    type: Opaque                                      # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  {{- end }}
  parameters:
    usePodIdentity: {{ .Values.secretProvider.usePodIdentity | quote }} # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: {{ .Values.secretProvider.keyVaultName }}             # the name of the KeyVault
    cloudName: ""                                                       # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects: {{ .Values.secretProvider.secretObject | quote }}          # nindent 6 | 
    resourceGroup: ""                                                   # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: ""                                                  # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: {{ .Values.secretProvider.tenantId }}                     # the tenant ID of the KeyVault
{{- end }}